api_test/api/views.py
__author__ = "shikun"
from flask import Flask, request, session, redirect, url_for, abort, \
     render_template, flash,jsonify, Blueprint
import db_base, const
from api_test.utilities import *

mysqlet = db_base.MySQLet(host="127.0.0.1", user="root", password="", charset="utf8", database="api", port=3306)
api = Blueprint('api', __name__, template_folder='templates',  static_folder='static')

@api.route("/list/<id>", methods=['GET'])
def list(id):
    apis = (mysqlet.findKeySql(const.FIND_ALL_BY_ATTR, table="api_info", criteria= {"where": "m_id=" + id}, whole=True))
    id = id
    return render_template("list.html", apis=apis, id=id)

@api.route("/add_api_h")
def add_api_h():
    return render_template('add_api.html')
@api.route('/add_api', methods=['POST'])
def add_api():
    mysqlet.findKeySql(const.INSERT, table="api_info", data={"title":  request.form['title'], "url":  request.form['url'], "param":  request.form['param'],
                                                             "method": request.form['m_method'], "hope_result": request.form['hope_result'],"result": 0,
                                                             "m_id": request.form["mondule_id"]})
    return redirect(url_for('moudle.mondule_info', id=request.form["mondule_id"]))

@api.route("/del_api", methods=["POST"])
def del_api():
    if mysqlet.findKeySql(const.DELETE_BY_ATTR, table="api_info", params={"id": request.form["id"]}):
        return jsonify({'msg': 1})
    else:
        return jsonify({'msg': 0})

api_test/api/templates/add_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{{url_for('api.static', filename='jquery-1.11.2.min.js')}}"></script>
        <!--<script src="{{url_for('api.static', filename='add_api.js')}}"></script>-->


</head>
<body>
<form action="{{ url_for('api.add_api') }}" method=post class=add_api>
      <ul>
        <li>名称<input type="text" size="10" name="title"></li>
        <li>url<input type="text" size="10" name="url"></li>
        <li>method<select id="sel_method">
            <option value="0">get</option>
            <option value="1">post</option>
        </select></li>
          <li><p id="btn_param" style="cursor:pointer">新增请求参数</p></li>
        <li class="param">
            参数
            <input type="text" name="param_name">
            <select class="sel_pram_type">
              <option value="0">数值型</option>
              <option value="1">字符串</option>
              <option value="2">浮点</option>
            </select>
            <select class="sel_param_value">
                <option value="0">非必填</option>
                <option value="1">必填</option>
            </select>
        </li>
           <li><p id="btn_param_hope" style="cursor:pointer">新增响应参数</p></li>
           <li class="param_hope">预期值
            <input type="text" name="param_hope_name">
            <select class="sel_pram_hope_type">
              <option value="0">数值型</option>
              <option value="1">字符串</option>
              <option value="2">浮点</option>
            </select>
            <select class="sel_param_hope_value">
                <option value="0">非必填</option>
                <option value="1">必填</option>
            </select>
        </li>
      </ul>
      <input type="hidden"  name="mondule_id" value="{{request.args.get('id')}}" >
      <input type="submit">
    </form>
</body>
</html>

api_test/api/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{{url_for('api.static', filename='jquery-1.11.2.min.js')}}"></script>
    <script src="{{url_for('api.static', filename='moudle.js')}}"></script>

</head>
<body>
<div><a href="{{ url_for('api.add_api_h', id=id) }}">新增api</a></div>
<div><a href="/test_api.html">开始测试</a></div>
  <table id="api">
    <thead>
        <tr>
            <th>标题</th>
            <th>url</th>
            <th>method</th>
            <th>请求参数</th>
            <th>预期值</th>
            <th>实际值</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    {% if apis != None %}
    {% for item in apis %}
        <tr id="{{item.id}}">
            <td>{{item.title}}</td>
            <td>{{item.url}}</td>
            <td>{{item.method}}</td>
            <td>{{item.param}}</td>
            <td>{{item.hope_result}}</td>
            {%if item.result == 0 %}
            <td>未测试</td>
            {% endif %}
            {% if item.result == 1 %}
             <td>通过</td>
            {% endif %}
             {% if item.result == 2 %}
            <td>失败</td>
             {% endif %}
            <td>
                <button class="del" >删除</button>
            </td>
        </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>
</body>
</html>