api_test/moudle/views.py
__author__ = "shikun"
from flask import Flask, request, session, redirect, url_for, abort, \
     render_template, flash,jsonify, Blueprint
import db_base, const
from api_test.utilities import *
from api_test import api
mysqlet = db_base.MySQLet(host="127.0.0.1", user="root", password="", charset="utf8", database="api", port=3306)
moudle = Blueprint('moudle', __name__, template_folder='templates', static_folder='static')

@moudle.route('/')
def index():
    moudles = mysqlet.findKeySql(const.FIND_BY_ALL, sql="select * from moudle" )
    print(moudles)
    return render_template('index.html', moudles=moudles)

@moudle.route('/add_moudle_h')
def add_moudle_h():
    return render_template('add_moudle.html')

@moudle.route('/mondule_info/<id>')
def mondule_info(id):
    apis = (mysqlet.findKeySql(const.FIND_ALL_BY_ATTR, table="api_info", criteria= {"where": "m_id=" + id}, whole=True))
    print(apis)
    id = id
    return render_template('mondule_info.html', apis=apis, id=id)
    # return redirect(url_for("api.list", id=id))

@moudle.route('/add_moudle', methods=['POST'])
def add_moudle():
    mysqlet.findKeySql(const.INSERT, table="moudle", data={"title": request.form['title'], "host": request.form['host'],
                        "port":request.form.get('port'), "header": request.form.get('header')})
    return redirect(url_for('index'))

api_test/moudle/templates/add_moudle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{{ url_for('moudle.add_moudle') }}" method=post class=add_moudle>
      <ul>
        <li>名称<input type="text" size="10" name="title"></li>
        <li>域名<input type="text" size="10" name="host"></li>
        <li>端口<input type="number" size="10" name="port" ></li>
        <li>请求头<textarea  name="header" ></textarea></li>
        <li>
          <input type="submit">
        </li>
      </ul>
    </form>
</body>
</html>

api_test/moudle/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div><a href="{{ url_for('moudle.add_moudle_h')}}">新增模块</a></div>
  <table id="moudle">
    <thead>
        <tr>
            <th>模块名</th>
            <th>域名</th>
            <th>端口</th>
            <th>请求头</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    {% if moudles != None  %}
        {% for item in moudles%}
                <tr>
                    <td>{{item.title}}</td>
                    <td>{{item.host}}</td>
                    <td>{{item.port}}</td>
                    <td>{{item.header}}</td>
                    <td><a href="{{ url_for('api.list', id=item.id) }}">查看详情</a></td>
                </tr>
        {% endfor %}
    {% endif %}
    </tbody>
  </table>

</body>
</html>

api_test/moudle/templates/mondule_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{{url_for('api.static', filename='jquery-1.11.2.min.js')}}"></script>
    <!--<script src="{{url_for('api.static', filename='moudle.js')}}"></script>-->

</head>
<body>
<div><a href="{{ url_for('api.add_api_h', id=id) }}">新增api</a></div>
<div><a href="/test_api.html">开始测试</a></div>
  <table id="api">
    <thead>
        <tr>
            <th>标题</th>
            <th>url</th>
            <th>method</th>
            <th>请求参数</th>
            <th>预期值</th>
            <th>实际值</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    {% if apis != None %}
    {% for item in apis %}
        <tr id="{{item.id}}">
            <td>{{item.title}}</td>
            <td>{{item.url}}</td>
            <td>{{item.method}}</td>
            <td>{{item.param}}</td>
            <td>{{item.hope_result}}</td>
            {%if item.result == 0 %}
            <td>未测试</td>
            {% endif %}
            {% if item.result == 1 %}
             <td>通过</td>
            {% endif %}
             {% if item.result == 2 %}
            <td>失败</td>
             {% endif %}
            <td>
                <button class="del" >删除</button>
            </td>
        </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>


</body>
</html>